### ISSUE TITLE
Stack size, priority and other attributes

### ISSUE THREAD

**Issue by JonatanAntoni** [Benichou34/cmsis_cpp#1]
Hi @Benichou34,

Nice work. Piotr Grygorczuk has done a similar adoption for FreeRTOS [1].

My biggest doubt is the lack of control over stack size and priority.
I think having *all* threads at a default priority with a default stack size will never meet real world applications requirements. Hence it would be really beneficial to figure out how to overcome this limitation.

Using C++11 interfaces might still be valuable even if the thread construction (i.e. constructor calls) wouldn't be standard compliant anymore.

Cheers,
Jonatan

[1] https://www.codeproject.com/Articles/1278513/Cplusplus11-FreeRTOS-GCC

**Comment by Benichou34** [comment]
Hi @JonatanAntoni,

Sorry for this very late response.
Thank you for your comment.
You are right, I added an extra parameter on thread constructor for control stack size and priority.
